name: orderly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  supabase_flutter: ^2.8.1
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  image: ^4.1.7
  provider: ^6.0.5
  intl: ^0.20.1
  url_launcher: ^6.2.5
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib\assets\logos\logo_colored.png
    - lib\assets\icons\menu.png
    - lib\assets\icons\dashboard.png
    - lib\assets\icons\inventory.png
    - lib\assets\icons\reservation.png
    - lib\assets\icons\staff.png
    - lib\assets\icons\table.png
    - lib\assets\logos\logo_colored_white.png
    - .env
  fonts:
    - family: Roboto
      fonts:
        - asset: lib\assets\fonts\Roboto-Medium.ttf
    - family: Poppins
      fonts:
        - asset: lib\assets\fonts\Poppins-Medium.ttf
    - family: Poppins-Italic
      fonts:
        - asset: lib\assets\fonts\Poppins-MediumItalic.ttf




  